[package]
name = "legal-document-be"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "4", features = [
    "macros",
    "cookies",
    "secure-cookies",
] }
actix-session = { version = "0.7", features = ["cookie-session"] }
actix-identity = "0.5.2"
env_logger = "0.10.0"
log = "0.4.20"
serde = { version = "1.0", features = ["derive"] }
